### ISSUE TITLE
Update standard deviation to current number

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/swti#53]
Per Rick T:

> Back in the spring NOAA updated to the 1991-2020 baseline for normals and these were implemented in the Statewide temperature index tool. One thing we did not do was to update value of standard deviation of the index
>
> 1981-2010 was 0.71074 (old)
> 1991-2020 should be 0.69423 (new)

The line that needs to be fixed is [here](https://github.com/ua-snap/swti/blob/acdc03dd3ee8c9eec1132e733d5303f47cc93696/data.py#L88) and the repo should be scanned for other instances of that value.

**Comment by cstephen** [comment]
This was fixed in b4914583ae2bca4be39146c1bfc7688984ec68b2.
